version: 0.7.{build}
branches:
  only:
  - master

skip_tags: true

image: 
- Visual Studio 2017
- Ubuntu

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  DOCKER_USERNAME:
    secure: 9W6f/+WW8NxmRbI1PQVsEQ==
  DOCKER_PASSWORD:
    secure: NxR5W82bWZsgr9cNAWaH+A==

install:
- sh: >-
    nvm install 8.11.2
    nvm use 8.11.2

build:
  project: src/MiningMonitor.sln
  verbosity: minimal

for:
-
  matrix:
    only: 
    - image: Visual Studio 2017
  
  before_build:
  - ps: >-
      nuget restore src\MiningMonitor.sln

      ((Get-Content -path src\MiningMonitor.WindowsService.Installer\MiningMonitor.wxs -Raw) -replace '\s+Version=\"[0-9]\.[0-9]\.[0-9]\.[0-9]\"'," Version=""$($env:APPVEYOR_BUILD_VERSION)""") | Set-Content -Path src\MiningMonitor.WindowsService.Installer\MiningMonitor.wxs

  build_script:
  - cmd: msbuild "%APPVEYOR_BUILD_FOLDER%\src\MiningMonitor.sln" /p:Configuration=WindowsService /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  artifacts:
  - path: '**\*.msi'

  deploy:
    release: MiningMonitor-v$(appveyor_build_version)
    provider: GitHub
    auth_token:
      secure: k/etfEesYPpZOMWmeHY+ZOdMzN45G9VS5dMvkxlzfvUBD1j+HrsJ/WeWAw9PoyBB
    artifact: /.*\.msi/
    draft: false
    prerelease: false
    on:
      branch: master
-
  matrix:
    only: 
    - image: Ubuntu

  build: off

  test: off

  deploy_script:
  - sh: >-
      docker build -f src/MiningMonitor.Web/Dockerfile -t "lennykean/miningmonitor:latest" -t "lennykean/miningmonitor:$APPVEYOR_BUILD_VERSION" src
      
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      
      docker push lennykean/miningmonitor