version: 0.9.{build}
branches:
  only:
  - master

skip_tags: true

image: 
- Visual Studio -
- Ubuntu

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  DOCKER_USERNAME:
    secure: 9W6f/+WW8NxmRbI1PQVsEQ==
  DOCKER_PASSWORD:
    secure: NxR5W82bWZsgr9cNAWaH+A==

install:
- sh: >-
    nvm install 12
    nvm use 12

build:
  project: src/MiningMonitor.sln
  verbosity: minimal

for:
-
  matrix:
    only: 
    - image: Visual Studio 2017
  
  before_build:
  - ps: >-
      nuget restore src\MiningMonitor.sln

      ((Get-Content -path src\MiningMonitor.WindowsService.Installer\MiningMonitor.wxs -Raw) -replace '\s+Version=\"[0-9]\.[0-9]\.[0-9]\.[0-9]\"'," Version=""$($env:APPVEYOR_BUILD_VERSION)""") | Set-Content -Path src\MiningMonitor.WindowsService.Installer\MiningMonitor.wxs

  build_script:
  - ps: >-
      msbuild src\MiningMonitor.sln /p:Configuration=WindowsService /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      
      dotnet publish -c Release src\MiningMonitor.Web

      Compress-Archive -Path src\MiningMonitor.Web\bin\Release\netcoreapp2.1\publish\* -DestinationPath .\miningmonitor.zip
      
      Compress-Archive -Path src\MiningMonitor.Web\bin\Release\netcoreapp2.1\publish\ClientApp\dist\* -DestinationPath .\clientapp.zip
      
      dotnet publish -c Release src\MiningMonitor.Workers.AlertScan
      
      Compress-Archive -Path src\MiningMonitor.Workers.AlertScan\bin\Release\netcoreapp2.1\publish\* -DestinationPath .\alertscan.zip
      
      dotnet publish -c Release src\MiningMonitor.Workers.DataCollector
      
      Compress-Archive -Path src\MiningMonitor.Workers.DataCollector\bin\Release\netcoreapp2.1\publish\* -DestinationPath .\datacollector.zip
      
      dotnet publish -c Release src\MiningMonitor.Workers.DataSynchronizer
      
      Compress-Archive -Path src\MiningMonitor.Workers.DataSynchronizer\bin\Release\netcoreapp2.1\publish\* -DestinationPath .\datasynchronizer.zip
      
      dotnet publish -c Release src\MiningMonitor.Workers.Maintenance
      
      Compress-Archive -Path src\MiningMonitor.Workers.Maintenance\bin\Release\netcoreapp2.1\publish\* -DestinationPath .\maintenance.zip
      
  artifacts:
  - path: '**\*.msi'
    name: WindowsInstaller
  - path: '**\*.zip'
    name: ServerlessAssets

  deploy:
    release: MiningMonitor-v$(appveyor_build_version)
    provider: GitHub
    auth_token:
      secure: POkCcSMbhpf3E+QVyiFvic5k2wfqITtPJgiQ4ZlOWd0aWtBqNbufAEWwHQkaleiD
    artifact: WindowsInstaller, ServerlessAssets
    draft: false
    prerelease: false
    on:
      branch: master
-
  matrix:
    only: 
    - image: Ubuntu

  build: off

  test: off

  deploy_script:
  - sh: >-
      docker build -f src/MiningMonitor.Web/Dockerfile -t "lennykean/miningmonitor:latest" -t "lennykean/miningmonitor:$APPVEYOR_BUILD_VERSION" src
      
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      
      docker push lennykean/miningmonitor