AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  MongoConnectionString:
    Type: String
  CodeS3Bucket: 
    Type: String

Globals:
  Function:
    Runtime: dotnetcore2.1
    Timeout: 60
    Environment:
      Variables:
        ConnectionStrings__miningmonitor: !Ref MongoConnectionString

Resources:
  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - 
          Effect: Allow
          Principal:
            Service: 
            - lambda.amazonaws.com
          Action: 
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: MiningMonitorWorkerRole

  AlertScan:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MiningMonitor.Workers.AlertScan::MiningMonitor.Workers.AlertScan.Program::Main
      CodeUri: 
        Bucket: !Ref CodeS3Bucket
        Key: alertscan.zip
      FunctionName: MiningMonitorAlertScan
      Role: !GetAtt WorkerRole.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: "null"

  DataCollector:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MiningMonitor.Workers.DataCollector::MiningMonitor.Workers.DataCollector.Program::Main
      CodeUri: 
        Bucket: !Ref CodeS3Bucket
        Key: datacollector.zip
      FunctionName: MiningMonitorDataCollector
      Role: !GetAtt WorkerRole.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: "null"

  DataSynchronizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MiningMonitor.Workers.DataSynchronizer::MiningMonitor.Workers.DataSynchronizer.Program::Main
      CodeUri: 
        Bucket: !Ref CodeS3Bucket
        Key: datasynchronizer.zip
      FunctionName: MiningMonitorDataSynchronizer
      Role: !GetAtt WorkerRole.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: "null"

  Maintenance:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MiningMonitor.Workers.Maintenance::MiningMonitor.Workers.Maintenance.Program::Main
      CodeUri: 
        Bucket: !Ref CodeS3Bucket
        Key: maintenance.zip
      FunctionName: MiningMonitorMaintenance
      Role: !GetAtt WorkerRole.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: "null"